# Generated by Django 5.0.6 on 2024-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tfn', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='Registro')),
                ('asistentes', models.IntegerField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
