# Generated by Django 5.0.7 on 2024-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_registro_asistentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='asistentes',
            new_name='Asistentes',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='tfn',
            new_name='Teléfono',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='imagen',
        ),
        migrations.AddField(
            model_name='registro',
            name='Imágen',
            field=models.ImageField(default=0, upload_to='Registro', verbose_name='Sube tu foto preferida'),
            preserve_default=False,
        ),
    ]
