# Generated by Django 5.0.6 on 2024-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='tfn',
        ),
        migrations.AddField(
            model_name='formulario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Formulario'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
