# Generated by Django 5.0.6 on 2024-07-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_remove_formulario_tfn_formulario_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ruta',
            field=models.CharField(choices=[('carro', 'carro'), ('route2', 'Route 2'), ('route3', 'Route 3')], default='route1', max_length=20),
        ),
    ]
