# Generated by Django 5.0.6 on 2024-07-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_formulario_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='title',
        ),
    ]
