# Generated by Django 5.0.6 on 2024-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_remove_formulario_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tfn',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
